export { adminApi } from './adminApiService';
export { authApi } from './authApiService';
export { avaliacaoApi } from './avaliacaoApiService';
export { clienteApi } from './clienteApiService';
export { cupomApi } from './cupomApiService';
export { elibrosApi } from './api';
export { freteApi } from './freteApiService';
export { livroApi } from './livroApiService';
export { pedidoApi } from './pedidoApiService';